# --
# config

# symbol converter
symbol_converter:

  # files and dirs
  #input_file: "./test_symbols.h"
  input_file: "/world/dekutree/git/aut/code/cpu/symbols.c"
  dirs:
    out_pgm: "./ignore/out/"
    in_pgm: "./ignore/out/"
    out_sym: "./ignore/out/symbols/"

  output_file_c: "symbols.c"
  output_file_h: "symbols.h"

  # print scaled
  print_scaled_img: True

  # conversion flags
  symbol_to_bmp: True
  bmp_to_symbol: True