
# for symbol converter
symbol_converter:
  #input_file: "./test_symbols.h"
  input_file: "/world/dekutree/git/aut/code/cpu/symbols.h"
  output_file_c: "./ignore/out/out_symbols.c"
  output_file_h: "./ignore/out/out_symbols.h"
  dirs:
    out_pgm: "./ignore/out/"
    in_pgm: "./ignore/out/"

  print_scaled_img: False